### ISSUE TITLE
1.1.0 does not exist

### ISSUE THREAD

**Issue by matthewhutchings** [Loschcode/vue-mixpanel#11]
yarn add vue-mixpanel@1.1.0 --save

yarn add v1.22.19
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "vue-mixpanel" that matches "1.1.0"
? Please choose a version of "vue-mixpanel" from this list: 
  2.0.0 
  1.0.7 
❯ 1.0.6 
  1.0.5 
  1.0.4 
  1.0.3 
  1.0.2 
  1.0.1 
  1.0.0

**Comment by Loschcode** [comment]
I had to remove this one as it wasn't working properly, and decided to go ahead and publish the 2.0.0 directly, could you use this one? It's with Vue3.
