### ISSUE TITLE
Pb on Netlify server 

### ISSUE THREAD

**Issue by TonyTR** [Loschcode/vue-mixpanel#2]
Hello @Loschcode 
i installed without problems and local in a nuxtjs project but once I have this err : Uncaught TypeError: Cannot read property 'persistence_name' of undefined
i don't see how to solve this.
Thx 
Tony

**Comment by TonyTR** [comment]
i tested with it mixpanel.init('MY TOKEN', {persistence: 'localStorage'}); but noway ..

**Comment by Loschcode** [comment]
Can you give me the full code you used that produces this error and your stack?

**Comment by TonyTR** [comment]
hello @Loschcode .. pb solved ...
