### ISSUE TITLE
The event is tracked twice if there is a redirect in function.

### ISSUE THREAD

**Issue by ReDss-TS** [Loschcode/vue-mixpanel#3]
I have component Register with method "success".
```
success() {
    this.$analytic.mixpanel.track('Sign Up', this.$analytic.mixpanel.getUserProperties());
    window.location = '/';
},
```

vue-mixpanel connected in my custom plugin Analytic
```
Vue.prototype.$analytic = {
    mixpanel: {
        track(eventName, properties) {
            mixpanelEventCallback(() => {
                this.identify();
                Vue.prototype.$mixpanel.track(eventName, properties);
            });
        },
        identify() {
            const userId = store.getters['user/getId'];

            if (userId !== undefined) {
                const identify = () => {
                    Vue.prototype.$mixpanel.identify(userId);
                };

                mixpanelEventCallback(identify);
            } else {
                mixpanelEventCallback(() => Vue.prototype.$mixpanel.reset());
            }
        },
    },
};
```
after logging in the event is tracked twice:
![image](https://user-images.githubusercontent.com/30149249/103641230-1d2be900-4f5a-11eb-8c1e-b8076a71a94e.png)
But the function is called only once.  If I set debug: true, in the console I can see MIXPANEL REQUEST log before and after redirect. So it is possible that mixpanel holds some information in cookies about the request but because there is a redirect it repeats it.

**Comment by Loschcode** [comment]
@ReDss-TS are you sure your `success()` or `mixpanelEventCallback()` isn't called twice?
