### ISSUE TITLE
Import not working with Vue3/Typescript

### ISSUE THREAD

**Issue by savannahp** [Loschcode/vue-mixpanel#7]
When trying to import import VueMixpanel from 'vue-mixpanel' I get the following error

**Could not find a declaration file for module 'vue-mixpanel'. '/Users/***/node_modules/vue-mixpanel/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vue-mixpanel` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-mixpanel';**

**Comment by Loschcode** [comment]
There's currently no support for TypeScript in this plugin, I'll need to investigate and adapt it.

**Comment by Loschcode** [comment]
@savannahp I've reworked the library to use Vue3 as well. It should be fine for the TS part starting from 1.1.0. Let me know if you have any more problem.
